Repository kube-vip/kube-vip, pull requests merged in 2020-11, with the labels that each got.

#93 Make port configurable
  cmd/kube-vip-start.go
  cmd/kube-vip.go
  pkg/cluster/clusterLeader.go
  pkg/kubevip/config_generator.go
  pkg/kubevip/config_types.go
Labels: control plane, enhancement

#95 Fixes to int parsing
  pkg/kubevip/config_generator.go
Labels: bug

#94 Adds documents into repo
  docs/architecture/index.md
  docs/architecture/kubernetes-vip-architecture.png
  docs/control-plane/0.1.4/index.md
  docs/control-plane/0.1.5/index.md
  docs/control-plane/index.md
  docs/index/index.md
  docs/index/kube-vip.png
  docs/kubernetes/index.md
  docs/manifests/controller.yaml
  docs/manifests/controller_test.yaml
  docs/manifests/kube-vip.yaml
Labels: documentation

#98 LoadBalancer Service changes
  Makefile
  pkg/cluster/singleNode.go
  pkg/service/services.go
Labels: type:LoadBalancer

#96 This adds upnp functionality to kube-vip
  Makefile
  go.mod
  go.sum
  pkg/service/manager.go
  pkg/service/services.go
Labels: enhancement, type:LoadBalancer

#100 This initial PR begins the work of using BGP as the load-balancer
  Makefile
  cmd/kube-vip-config.go
  cmd/kube-vip-start.go
  cmd/kube-vip.go
  docs/manifests/controller.yaml
  docs/manifests/controller_test.yaml
  go.mod
  go.sum
  pkg/cluster/clusterLeader.go
  pkg/cluster/clusterRaft.go
  pkg/cluster/singleNode.go
  pkg/kubevip/config_generator.go
  pkg/kubevip/config_types.go
  pkg/service/manager.go
  pkg/service/manager_arp.go
  pkg/service/manager_bgp.go
  pkg/service/services.go
  pkg/service/watcher.go
Labels: enhancement, type:LoadBalancer

#102 Fix typo on README
  README.md
Labels: documentation

#99 add dynamic dns support with dhcp for apiserver vip
  cmd/kube-vip-start.go
  go.mod
  go.sum
  pkg/cluster/cluster.go
  pkg/cluster/clusterDDNS.go
  pkg/cluster/clusterLeader.go
  pkg/kubevip/config_generator.go
  pkg/kubevip/config_types.go
  pkg/vip/address.go
  pkg/vip/ddns.go
  pkg/vip/dns.go
  pkg/vip/util.go
Labels: control plane, enhancement

#109 BGP Fixes
  Makefile
  pkg/kubevip/config_generator.go
  pkg/service/services.go
Labels: bug, type:LoadBalancer
